# Define the system of units to use internally. 
InternalUnitSystem:
  UnitMass_in_cgs:     1.98841e43    # 10^10 M_sun
  UnitLength_in_cgs:   3.08567758e24 # 1 Mpc
  UnitVelocity_in_cgs: 1e5           # 1 km/s
  UnitCurrent_in_cgs:  1             # Amperes
  UnitTemp_in_cgs:     1             # Kelvin

# Planck-13 cosmology
Cosmology:
  h:              $HubbleParam      # Reduced Hubble constant
  a_begin:        $starting_a       # Initial scale-factor of the simulation
  a_end:          $finishing_a      # Final scale factor of the simulation
  Omega_cdm:      $OmegaCDM         # Cold Dark Matter density parameter
  Omega_lambda:   $OmegaLambda      # Dark-energy density parameter
  Omega_b:        $OmegaBaryon      # Baryon density parameter

# Parameters governing the time integration
TimeIntegration:
  dt_min:     1e-6 
  dt_max:     0.01

Scheduler:
  max_top_level_cells:  64
  cell_split_size:      200
  tasks_per_cell:       3

# Parameters governing the snapshots
Snapshots:
  basename:             $f_name
  delta_time:           1.02
  scale_factor_first:   0.02
  output_list_on:       1
  output_list:          snapshot_times.txt
  subdir:               snapshots 
  distributed:          1
  compression:          0
  select_output_on:     1
  select_output:        select_output.yml
  invoke_fof:           1

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1.02
  scale_factor_first:  0.02
 
# Restart files.
Restarts:
  enable:               1
  delta_hours:          6.0
  max_run_time:         71.5         # In hours
  onexit:               1

# Parameters for the self-gravity scheme
Gravity:
  eta:                              0.025         
  comoving_DM_softening:            $eps_dm
  softening_ratio_background:       $softening_ratio_background
  max_physical_DM_softening:        $eps_dm_physical
  mesh_side_length:                 1024
  MAC:                              adaptive
  theta_cr:                         0.7
  epsilon_fmm:                      0.001
  allow_truncation_in_MAC:          1
  use_tree_below_softening:         1

# Parameters related to the initial conditions
InitialConditions:
  file_name:                   $swift_ic_dir_loc/$f_name.hdf5
  periodic:                    1
  cleanup_h_factors:           1    
  cleanup_velocity_factors:    1

# FOF for HBT.
FOF:
  min_group_size:               20
  linking_length_ratio:         0.2
  seed_black_holes_enabled:     0
  basename:                     $f_name
