#!/bin/bash -l

#SBATCH --ntasks=XXX
#SBATCH -J XXX
#SBATCH --output=out_files/log_%j.txt
#SBATCH -p cosma7
#SBATCH -A dp004
#SBATCH --exclusive
#SBATCH --cpus-per-task=28
#SBATCH --time=XXX:00:00

load_swift_c7_old

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

mpirun -np $SLURM_NTASKS ../../swiftsim/examples/swift_mpi -v 1 --pin --cosmology --self-gravity --threads=$SLURM_CPUS_PER_TASK --velociraptor params.yml

echo "Job done, info follows..."
sacct -j $SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit
