#!/bin/bash -l

#SBATCH --ntasks=$n_cores_ic_gen
#SBATCH --job-name=$f_name
#SBATCH --output=log_%j.txt
#SBATCH --partition=cosma7
#SBATCH --account=dp004
#SBATCH --exclusive
#SBATCH --time=$num_hours_ic_gen:00:00

module purge
module load intel_comp/2018 intel_mpi/2018 fftw/3.3.9cosma7 gsl/2.5 hdf5/1.10.3 cmake/3.18.1

cd ../../

mpirun -env I_MPI_PIN=1 -env I_MPI_PIN_PROCESSOR_LIST=allcores -np $$SLURM_NTASKS ./IC_Gen.x ./ic_gen_submit_files/$f_name/params.inp

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit

